### ISSUE TITLE
What is the best approach for data with online logging first?

### ISSUE THREAD

**Issue by kunstler** [ropenscilabs/laselva#10]
Several data set are accessible only after login on a web-page where you need to enter your email and then you get a confirmation email which allow you to download the data.
For instance http://inventaire-forestier.ign.fr/spip/spip.php?article532
 
One solution would be to print a text explaining that you need to fill in the form and that you will get an email with the link to the data.
Opening the website with
```
browseURL("http://inventaire-forestier.ign.fr/spip/spip.php?article532")
```
Then you get an email with a link with a token (replace by SOMETHING here) like that 'http://inventaire-forestier.ign.fr/spip/spip.php?article707&ID_TELECHARGEMENT=16609&TOKEN=SOMETHING'

With zip files coming each with their own links such as 'http://inventaire-forestier.ign.fr/spip/IMG/zip/placette-foret-2.zip'

What would be the best approach to download this ? And where to save them? I see you are using `rappdirs` but not sure how do that from there.

Scott you probably know much more than me on these web issues. What would be your approach (how to deal with these token?)?

**Comment by sckott** [comment]
Good question @kunstler 

think in each case will depend on the license - in many cases I bet there won't be a proper license, but something like found on the website in question here - which from my reading at least suggests there's nothing stopping us from re-distributing the data - correct?  or am i wrong?  If the data are small enough we can include them in the pkg, but if too big then we shouldn't include in pkg

**Comment by kunstler** [comment]
From what I read in the data use agrement of the French NFI ('Ils peuvent être téléchargés gratuitement et les données contenues dans les fichiers peuvent être réutilisées, y compris à des fins commerciales, sans licence et sans versement de redevance.') it seems possible as they say that data can be reused even for commercial purpose.

French NFI data un-compressed is around 100MB

For the Italian data I can't find anything about the data re-use. I will ask aldo if he can find anything about that in Italian.

**Comment by sckott** [comment]
Okay, 100 MB is too big, though we'll see what it is when compressed. Probably will have to host it somewhere like github or amazon s3, and download from there
