### ISSUE TITLE
post-processing

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/laselva#4]
what are the post-processing things FIA users often do?  could add those things

**Comment by kunstler** [comment]
Common tasks with NFI data (not only FIA data but in general) are:
- compute individual growth and survival 
- compute basal area or number of individual per hectare on each plot (per species or total)
- filter out plots with change in protocol (or harvesting)
- get climatic data from plots coordinates
- get species traits

To do that ideally what we would need is to homogenize the different NFI source to a common structure. We would need 
- unique obs id
- unique tree id 
- unique plot id
- unique subplot id
- subplot weight (several NFI sample trees < dbh1 in a small subplot, trees between dbh1 and dbh2 in a medium subplot and trees bigger than dbh2 in a large subplot, to get estimate per hectare we need the area of the subplot)
- diameter at census 1 , 2, ... (common unit across NFI)
- date of census 1, 2, ...
- species (ideally checking against a common reference)
- plot coordinates in a common CSR
- variable on tree status (alive, dead, harvested, unknown)
- variable recording disturbance on plot
- variable recording issue with measurement on the plot (change of protocol, error, ...)

**Comment by sckott** [comment]
this is great, thanks @kunstler 

the climate and traits data may not be a good fit for this package, but we could show examples of how to link up with those data in examples/vignette

that'd be great to have functions to do the major operations you've listed

**Comment by sckott** [comment]
closing unless someone else wants to take this up
