### ISSUE TITLE
package API

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/laselva#9]
assuming we incorporate other data sources, the fxns:

same as now, but should rename by country?

* `list_datasets_usa()` 
* `fetch_usa()` 

new ones, by country or country code?

* `fetch_germany()` / or `de_fetch()`
* `fetch_spain()` / or `es_fetch()`

and for ones that are not country wide, e.g., name of the project, or region?

* `fetch_queensland()` for this dataset http://onlinelibrary.wiley.com/doi/10.1890/14-0458R.1/abstract

thoughts on what makes sense for target users of this data @kunstler

**Comment by kunstler** [comment]
I think country or region name is clearer.

**Comment by sckott** [comment]
thanks @kunstler
